// SESSION
export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAILURE = 'SESSION_FAILURE';
export const SESSION_DESTROY = 'SESSION_DESTROY';
export const UNAUTHENTICATED_REQUEST = 'UNAUTHENTICATED_REQUEST';

// USER
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

// AGENCIES
export const AGENCIES_SEARCH_REQUEST = 'AGENCIES_SEARCH_REQUEST';
export const AGENCIES_SEARCH_SUCCESS = 'AGENCIES_SEARCH_SUCCESS';
export const AGENCIES_SEARCH_FAILURE = 'AGENCIES_SEARCH_FAILURE';

// FILTERS
export const ARE_FILTERS_LOADING = 'ARE_FILTERS_LOADING';

// RATES

// RATES
export const RATES_REQUEST = 'RATES_REQUEST';
export const RATES_SUCCESS = 'RATES_SUCCESS';
export const RATES_FAILURE = 'RATES_FAILURE';
export const RATES_UPDATE = 'RATES_UPDATE';
export const RATES_BULK_UPDATE = 'RATES_BULK_UPDATE';
export const RATES_CLEAR = 'RATES_CLEAR';

// FILTERS
export const RATES_FILTERS_REQUEST = 'RATES_FILTERS_REQUEST';
export const RATES_FILTERS_SUCCESS = 'RATES_FILTERS_SUCCESS';
export const RATES_FILTERS_FAILURE = 'RATES_FILTERS_FAILURE';
export const RATES_FILTERS_RESET = 'RATES_FILTERS_RESET';
export const RATES_FILTER_UPDATE = 'RATES_FILTER_UPDATE';
export const RATES_FILTER_PIN_REQUEST = 'RATES_FILTER_PIN_REQUEST';
export const RATES_FILTER_PIN_SUCCESS = 'RATES_FILTER_PIN_SUCCESS';
export const RATES_FILTER_PIN_FAILURE = 'RATES_FILTER_PIN_FAILURE';
export const RATES_FILTER_CLEAR_VALUE = 'RATES_FILTER_CLEAR_VALUE';

// FILTER TABS
export const RATES_FILTER_TAB_CHANGE = 'RATES_FILTER_TAB_CHANGE';

// VIEW FILTER
export const RATES_VISIBLE_CHANNELS_UPDATE = 'RATES_VISIBLE_CHANNELS_UPDATE';
export const RATES_UNIT_SCOPE_UPDATE = 'RATES_UNIT_SCOPE_UPDATE';

// STORAGE
export const RATES_STORAGE_SAVE_START = 'RATES_STORAGE_SAVE_START';
export const RATES_STORAGE_SAVE_END = 'RATES_STORAGE_SAVE_END';
export const RATES_STORAGE_LOAD_START = 'RATES_STORAGE_LOAD_START';
export const RATES_STORAGE_LOAD_END = 'RATES_STORAGE_LOAD_END';
export const RATES_STORAGE_CLEAR = 'RATES_STORAGE_CLEAR';

// INVENTORY
export const INVENTORY_REQUEST = 'INVENTORY_REQUEST';
export const INVENTORY_SUCCESS = 'INVENTORY_SUCCESS';
export const INVENTORY_FAILURE = 'INVENTORY_FAILURE';
export const INVENTORY_UPDATE = 'INVENTORY_UPDATE';
export const INVENTORY_BULK_UPDATE = 'INVENTORY_BULK_UPDATE';
export const INVENTORY_CLEAR = 'INVENTORY_CLEAR';

// FILTERS
export const INVENTORY_FILTERS_REQUEST = 'INVENTORY_FILTERS_REQUEST';
export const INVENTORY_FILTERS_SUCCESS = 'INVENTORY_FILTERS_SUCCESS';
export const INVENTORY_FILTERS_FAILURE = 'INVENTORY_FILTERS_FAILURE';
export const INVENTORY_FILTERS_RESET = 'INVENTORY_FILTERS_RESET';
export const INVENTORY_FILTER_UPDATE = 'INVENTORY_FILTER_UPDATE';
export const INVENTORY_FILTER_PIN_REQUEST = 'INVENTORY_FILTER_PIN_REQUEST';
export const INVENTORY_FILTER_PIN_SUCCESS = 'INVENTORY_FILTER_PIN_SUCCESS';
export const INVENTORY_FILTER_PIN_FAILURE = 'INVENTORY_FILTER_PIN_FAILURE';
export const INVENTORY_FILTER_CLEAR_VALUE = 'INVENTORY_FILTER_CLEAR_VALUE';

// FILTER TABS
export const INVENTORY_FILTER_TAB_CHANGE = 'INVENTORY_FILTER_TAB_CHANGE';

// VIEW FILTER
export const INVENTORY_VISIBLE_CHANNELS_UPDATE =
  'INVENTORY_VISIBLE_CHANNELS_UPDATE';
export const INVENTORY_UNIT_SCOPE_UPDATE = 'INVENTORY_UNIT_SCOPE_UPDATE';

// STORAGE
export const INVENTORY_STORAGE_SAVE_START = 'INVENTORY_STORAGE_SAVE_START';
export const INVENTORY_STORAGE_SAVE_END = 'INVENTORY_STORAGE_SAVE_END';
export const INVENTORY_STORAGE_LOAD_START = 'INVENTORY_STORAGE_LOAD_START';
export const INVENTORY_STORAGE_LOAD_END = 'INVENTORY_STORAGE_LOAD_END';
export const INVENTORY_STORAGE_CLEAR = 'INVENTORY_STORAGE_CLEAR';

// CHECKOUT

// TABS
export const CHECKOUT_ACTIVE_TAB_UPDATE = 'CHECKOUT_ACTIVE_TAB_UPDATE';

// INDEXDB
export const LOCAL_DATABASE_LOADED = 'LOCAL_DATABASE_LOADED';

// UNITS
export const CHECKOUT_UNIT_REMOVE = 'CHECKOUT_UNIT_REMOVE';
export const CHECKOUT_UNIT_LOAD = 'CHECKOUT_UNIT_LOAD';
export const CHECKOUT_UNIT_UPDATE = 'CHECKOUT_UNIT_UPDATE';

// SAVING UNITS
export const CHECKOUT_UNITS_SAVED = 'CHECKOUT_UNITS_SAVED';
export const CHECKOUT_UNITS_SAVING = 'CHECKOUT_UNITS_SAVING';
export const CHECKOUT_UNITS_RESET = 'CHECKOUT_UNITS_RESET';
export const CHECKOUT_UNITS_ERROR = 'CHECKOUT_UNITS_ERROR';
export const CHECKOUT_CLEAR_UNITS_ERROR = 'CHECKOUT_CLEAR_UNITS_ERROR';

// CHECKOUT ACTIVITY
export const CHECKOUT_ACTIVITY = 'CHECKOUT_ACTIVITY';

// HISTORY

// HISTORY
export const HISTORY_REQUEST = 'HISTORY_REQUEST';
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS';
export const HISTORY_FAILURE = 'HISTORY_FAILURE';
export const HISTORY_RESET = 'HISTORY_RESET';

// TABS
export const HISTORY_ACTIVE_TAB_UPDATE = 'HISTORY_ACTIVE_TAB_UPDATE';

// HISTORY FILTERS
export const HISTORY_FILTERS_REQUEST = 'HISTORY_FILTERS_REQUEST';
export const HISTORY_FILTERS_SUCCESS = 'HISTORY_FILTERS_SUCCESS';
export const HISTORY_FILTERS_FAILURE = 'HISTORY_FILTERS_FAILURE';
export const HISTORY_FILTERS_RESET = 'HISTORY_FILTERS_RESET';
export const HISTORY_FILTER_UPDATE = 'HISTORY_FILTER_UPDATE';
export const HISTORY_FILTER_PIN_REQUEST = 'HISTORY_FILTER_PIN_REQUEST';
export const HISTORY_FILTER_PIN_SUCCESS = 'HISTORY_FILTER_PIN_SUCCESS';
export const HISTORY_FILTER_PIN_FAILURE = 'HISTORY_FILTER_PIN_FAILURE';

// MEMBERS
export const MEMBERS_REQUEST = 'MEMBERS_REQUEST';
export const MEMBERS_SUCCESS = 'MEMBERS_SUCCESS';
export const MEMBERS_FAILURE = 'MEMBERS_FAILURE';
export const MEMBERS_RESET = 'MEMBERS_RESET';
export const MEMBERS_UPDATE = 'MEMBERS_UPDATE';
export const MEMBERS_UPDATE_SUCCESS = 'MEMBERS_UPDATE_SUCCESS';
export const MEMBERS_UPDATE_FAILURE = 'MEMBERS_UPDATE_FAILURE';
export const MEMBERS_CREATE = 'MEMBERS_CREATE';
export const MEMBERS_CREATE_SUCCESS = 'MEMBERS_CREATE_SUCCESS';
export const MEMBERS_CREATE_FAILURE = 'MEMBERS_CREATE_FAILURE';
export const MEMBERS_DELETE = 'MEMBERS_DELETE';
export const MEMBERS_DELETE_SUCCESS = 'MEMBERS_DELETE_SUCCESS';
export const MEMBERS_DELETE_FAILURE = 'MEMBERS_DELETE_FAILURE';
export const MEMBERS_ACTIVE_TAB_UPDATE = 'MEMBERS_ACTIVE_TAB_UPDATE';

// MEMBERS FILTERS
export const MEMBERS_FILTERS_REQUEST = 'MEMBERS_FILTERS_REQUEST';
export const MEMBERS_FILTERS_SUCCESS = 'MEMBERS_FILTERS_SUCCESS';
export const MEMBERS_FILTERS_FAILURE = 'MEMBERS_FILTERS_FAILURE';
export const MEMBERS_FILTERS_RESET = 'MEMBERS_FILTERS_RESET';
export const MEMBERS_FILTER_UPDATE = 'MEMBERS_FILTER_UPDATE';
export const MEMBERS_FILTER_PIN_REQUEST = 'MEMBERS_FILTER_PIN_REQUEST';
export const MEMBERS_FILTER_PIN_SUCCESS = 'MEMBERS_FILTER_PIN_SUCCESS';
export const MEMBERS_FILTER_PIN_FAILURE = 'MEMBERS_FILTER_PIN_FAILURE';

// PROPERTIES
export const PROPERTIES_REQUEST = 'PROPERTIES_REQUEST';
export const PROPERTIES_SUCCESS = 'PROPERTIES_SUCCESS';
export const PROPERTIES_FAILURE = 'PROPERTIES_FAILURE';
export const PROPERTIES_SEARCH_REQUEST = 'PROPERTIES_SEARCH_REQUEST';
export const PROPERTIES_SEARCH_SUCCESS = 'PROPERTIES_SEARCH_SUCCESS';
export const PROPERTIES_SEARCH_FAILURE = 'PROPERTIES_SEARCH_FAILURE';

// UNIT_TYPES
export const UNIT_TYPES_REQUEST = 'UNIT_TYPES_REQUEST';
export const UNIT_TYPES_SUCCESS = 'UNIT_TYPES_SUCCESS';
export const UNIT_TYPES_FAILURE = 'UNIT_TYPES_FAILURE';

// TOAST
export const TOAST_MESSAGE_ADD = 'TOAST_MESSAGE_ADD';
export const TOAST_MESSAGE_REMOVE_FIRST = 'TOAST_MESSAGE_REMOVE_FIRST';
export const TOAST_MESSAGE_REMOVE_TOAST = 'TOAST_MESSAGE_REMOVE_TOAST';

// FULLSCREEN
export const START_FULLSCREEN = 'START_FULLSCREEN';
export const END_FULLSCREEN = 'END_FULLSCREEN';

// NO_PADDING
export const START_NO_PADDING = 'START_NO_PADDING';
export const END_NO_PADDING = 'END_NO_PADDING';

// PASSWORD
export const PASSWORD_CREATE = 'PASSWORD_CREATE';
export const PASSWORD_CREATE_SUCCESS = 'PASSWORD_CREATE_SUCCESS';
export const PASSWORD_CREATE_FAILURE = 'PASSWORD_CREATE_FAILURE';

// PASSWORD RESET REQUEST
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

// PASSWORD PAGE RESET REQUEST
export const PASSWORD_PAGE_RESET_REQUEST = 'PASSWORD_PAGE_RESET_REQUEST';
export const PASSWORD_PAGE_RESET_SUCCESS = 'PASSWORD_PAGE_RESET_SUCCESS';
export const PASSWORD_PAGE_RESET_FAILURE = 'PASSWORD_PAGE_RESET_FAILURE';

// DASHBOARD FILTERS
export const DASHBOARD_FILTERS_REQUEST = 'DASHBOARD_FILTERS_REQUEST';
export const DASHBOARD_FILTERS_SUCCESS = 'DASHBOARD_FILTERS_SUCCESS';
export const DASHBOARD_FILTERS_FAILURE = 'DASHBOARD_FILTERS_FAILURE';
export const DASHBOARD_FILTERS_RESET = 'DASHBOARD_FILTERS_RESET';
export const DASHBOARD_FILTER_UPDATE = 'DASHBOARD_FILTER_UPDATE';
export const DASHBOARD_FILTER_SELECTED_OPTIONS_UPDATE =
  'DASHBOARD_FILTER_SELECTED_OPTIONS_UPDATE';
export const DASHBOARD_FILTER_PIN_REQUEST = 'DASHBOARD_FILTER_PIN_REQUEST';
export const DASHBOARD_FILTER_PIN_SUCCESS = 'DASHBOARD_FILTER_PIN_SUCCESS';
export const DASHBOARD_FILTER_PIN_FAILURE = 'DASHBOARD_FILTER_PIN_FAILURE';

// DASHBOARD
export const DASHBOARDS_REQUEST = 'DASHBOARDS_REQUEST';
export const DASHBOARDS_SUCCESS = 'DASHBOARDS_SUCCESS';
export const DASHBOARDS_FAILURE = 'DASHBOARDS_FAILURE';
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_CREATE_REQUEST = 'DASHBOARD_CREATE_REQUEST';
export const DASHBOARD_CREATE_SUCCESS = 'DASHBOARD_CREATE_SUCCESS';
export const DASHBOARD_CREATE_FAILURE = 'DASHBOARD_CREATE_FAILURE';
export const DASHBOARD_DELETE_REQUEST = 'DASHBOARD_DELETE_REQUEST';
export const DASHBOARD_DELETE_SUCCESS = 'DASHBOARD_DELETE_SUCCESS';
export const DASHBOARD_DELETE_FAILURE = 'DASHBOARD_DELETE_FAILURE';
export const DASHBOARD_EDIT_REQUEST = 'DASHBOARD_EDIT_REQUEST';
export const DASHBOARD_EDIT_SUCCESS = 'DASHBOARD_EDIT_SUCCESS';
export const DASHBOARD_EDIT_FAILURE = 'DASHBOARD_EDIT_FAILURE';
export const DASHBOARD_FILTER_BULK_UPDATE = 'DASHBOARD_FILTER_BULK_UPDATE';

// WIDGET
export const DASHBOARD_WIDGET_REQUEST = 'DASHBOARD_WIDGET_REQUEST';
export const DASHBOARD_WIDGET_SUCCESS = 'DASHBOARD_WIDGET_SUCCESS';
export const DASHBOARD_WIDGET_FAILURE = 'DASHBOARD_WIDGET_FAILURE';
export const WIDGET_RESET = 'WIDGET_RESET';
export const WIDGET_REQUEST = 'WIDGET_REQUEST';
export const WIDGET_SUCCESS = 'WIDGET_SUCCESS';
export const WIDGET_FAILURE = 'WIDGET_FAILURE';
export const WIDGET_CREATE_REQUEST = 'WIDGET_CREATE_REQUEST';
export const WIDGET_CREATE_SUCCESS = 'WIDGET_CREATE_SUCCESS';
export const WIDGET_CREATE_FAILURE = 'WIDGET_CREATE_FAILURE';
export const WIDGET_DELETE_REQUEST = 'WIDGET_DELETE_REQUEST';
export const WIDGET_DELETE_SUCCESS = 'WIDGET_DELETE_SUCCESS';
export const WIDGET_DELETE_FAILURE = 'WIDGET_DELETE_FAILURE';
export const WIDGET_EDIT_REQUEST = 'WIDGET_EDIT_REQUEST';
export const WIDGET_EDIT_SUCCESS = 'WIDGET_EDIT_SUCCESS';
export const WIDGET_EDIT_FAILURE = 'WIDGET_EDIT_FAILURE';
export const WIDGET_BULK_PLACEMENT_EDIT_REQUEST =
  'WIDGET_BULK_PLACEMENT_EDIT_REQUEST';
export const WIDGET_BULK_PLACEMENT_EDIT_SUCCESS =
  'WIDGET_BULK_PLACEMENT_EDIT_SUCCESS';
export const WIDGET_BULK_PLACEMENT_EDIT_FAILURE =
  'WIDGET_BULK_PLACEMENT_EDIT_FAILURE';
export const WIDGET_CATEGORIES_REQUEST = 'WIDGET_CATEGORIES_REQUEST';
export const WIDGET_CATEGORIES_SUCCESS = 'WIDGET_CATEGORIES_SUCCESS';
export const WIDGET_CATEGORIES_FAILURE = 'WIDGET_CATEGORIES_FAILURE';
export const WIDGET_METRICS_REQUEST = 'WIDGET_METRICS_REQUEST';
export const WIDGET_METRICS_SUCCESS = 'WIDGET_METRICS_SUCCESS';
export const WIDGET_METRICS_FAILURE = 'WIDGET_METRICS_FAILURE';
export const DUPLICATE_WIDGET_REQUEST = 'DUPLICATE_WIDGET_REQUEST';
export const DUPLICATE_WIDGET_SUCCESS = 'DUPLICATE_WIDGET_SUCCESS';
export const DUPLICATE_WIDGET_FAILURE = 'DUPLICATE_WIDGET_FAILURE';
export const RESET_WIDGET_CALCULATION_STATE = 'RESET_WIDGET_CALCULATION_STATE';
export const WIDGET_NAME_REQUEST = 'WIDGET_NAME_REQUEST';
export const WIDGET_NAME_SUCCESS = 'WIDGET_NAME_SUCCESS';
export const WIDGET_NAME_FAILURE = 'WIDGET_NAME_FAILURE';

// WIDGET WIZARD
export const WIDGET_VARIABLE_CREATE = 'WIDGET_VARIABLE_CREATE';
export const WIDGET_VARIABLE_EDIT = 'WIDGET_VARIABLE_EDIT';
export const WIDGET_VARIABLE_DELETE = 'WIDGET_VARIABLE_DELETE';
export const WIDGET_VARIABLES_BULK_CREATE = 'WIDGET_VARIABLES_BULK_CREATE';
export const WIDGET_VARIABLES_RESET = 'WIDGET_VARIABLES_RESET';
export const WIDGET_CALCULATOR_VALUE_CREATE = 'WIDGET_CALCULATOR_VALUE_CREATE';
export const WIDGET_CALCULATOR_VALUE_EDIT = 'WIDGET_CALCULATOR_VALUE_EDIT';
export const WIDGET_CALCULATOR_VALUE_DELETE = 'WIDGET_CALCULATOR_VALUE_DELETE';
export const WIDGET_CALCULATOR_VARIABLE_EDIT =
  'WIDGET_CALCULATOR_VARIABLE_EDIT';
export const WIDGET_CALCULATOR_RESET = 'WIDGET_CALCULATOR_RESET';
export const WIDGET_CALCULATOR_EDIT = 'WIDGET_CALCULATOR_EDIT';
export const WIDGET_CALCULATIONS_REQUEST = 'WIDGET_CALCULATIONS_REQUEST';
export const WIDGET_CALCULATIONS_SUCCESS = 'WIDGET_CALCULATIONS_SUCCESS';
export const WIDGET_CALCULATIONS_FAILURE = 'WIDGET_CALCULATIONS_FAILURE';
export const WIDGET_VALUE_CREATE = 'WIDGET_VALUE_CREATE';
export const WIDGET_VALUE_EDIT = 'WIDGET_VALUE_EDIT';
export const WIDGET_VALUE_VARIABLE_EDIT = 'WIDGET_VALUE_VARIABLE_EDIT';
export const WIDGET_VALUE_DELETE = 'WIDGET_VALUE_DELETE';
export const WIDGET_VALUES_UPDATE = 'WIDGET_VALUES_UPDATE';
export const WIDGET_VALUES_BULK_CREATE = 'WIDGET_VALUES_BULK_CREATE';
export const WIDGET_VALUES_RESET = 'WIDGET_VALUES_RESET';
export const RECENTLY_USED_VARIABLES_REQUEST =
  'RECENTLY_USED_VARIABLES_REQUEST';
export const RECENTLY_USED_VARIABLES_SUCCESS =
  'RECENTLY_USED_VARIABLES_SUCCESS';
export const RECENTLY_USED_VARIABLES_FAILURE =
  'RECENTLY_USED_VARIABLES_FAILURE';

// DISPLAY DENSITY
export const TABLE_DISPLAY_DENSITY_REQUEST = 'TABLE_DISPLAY_DENSITY_REQUEST';
export const TABLE_DISPLAY_DENSITY_SUCCESS = 'TABLE_DISPLAY_DENSITY_SUCCESS';
export const TABLE_DISPLAY_DENSITY_FAILURE = 'TABLE_DISPLAY_DENSITY_FAILURE';

// DASHBOARDS
export const DASHBOARD_ADD = 'DASHBOARD_ADD';
export const DASHBOARD_DELETE = 'DASHBOARD_DELETE';
export const DASHBOARD_EDIT = 'DASHBOARD_EDIT';

// FILTER SET
export const FILTER_SET_CREATE_REQUEST = 'FILTER_SET_CREATE_REQUEST';
export const FILTER_SET_CREATE_SUCCESS = 'FILTER_SET_CREATE_SUCCESS';
export const FILTER_SET_CREATE_FAILURE = 'FILTER_SET_CREATE_FAILURE';

export const FILTER_SET_EDIT_REQUEST = 'FILTER_SET_EDIT_REQUEST';
export const FILTER_SET_EDIT_SUCCESS = 'FILTER_SET_EDIT_SUCCESS';
export const FILTER_SET_EDIT_FAILURE = 'FILTER_SET_EDIT_FAILURE';

export const FILTER_SET_REQUEST = 'FILTER_SET_REQUEST';
export const FILTER_SET_SUCCESS = 'FILTER_SET_SUCCESS';
export const FILTER_SET_FAILURE = 'FILTER_SET_FAILURE';

export const FILTER_SET_DELETE_REQUEST = 'FILTER_SET_DELETE_REQUEST';
export const FILTER_SET_DELETE_SUCCESS = 'FILTER_SET_DELETE_SUCCESS';
export const FILTER_SET_DELETE_FAILURE = 'FILTER_SET_DELETE_FAILURE';

export const SET_ACTIVE_FILTER_SET = 'SET_ACTIVE_FILTER_SET';
export const SET_DEFAULT_FILTER_SET = 'SET_DEFAULT_FILTER_SET';

// OVERVIEW
export const OVERVIEW_FILTERS_REQUEST = 'OVERVIEW_FILTERS_REQUEST';
export const OVERVIEW_FILTERS_SUCCESS = 'OVERVIEW_FILTERS_SUCCESS';
export const OVERVIEW_FILTERS_FAILURE = 'OVERVIEW_FILTERS_FAILURE';
export const OVERVIEW_FILTERS_UPDATE = 'OVERVIEW_FILTERS_UPDATE';
export const OVERVIEW_FILTER_UPDATE = 'OVERVIEW_FILTER_UPDATE';
export const OVERVIEW_DATA_REQUEST = 'OVERVIEW_DATA_REQUEST';
export const OVERVIEW_DATA_SUCCESS = 'OVERVIEW_DATA_SUCCESS';
export const OVERVIEW_DATA_FAILURE = 'OVERVIEW_DATA_FAILURE';
export const OVERVIEW_ITEM_DETAILS_REQUEST = 'OVERVIEW_ITEM_DETAILS_REQUEST';
export const OVERVIEW_ITEM_DETAILS_SUCCESS = 'OVERVIEW_ITEM_DETAILS_SUCCESS';
export const OVERVIEW_ITEM_DETAILS_FAILURE = 'OVERVIEW_ITEM_DETAILS_FAILURE';
export const OVERVIEW_NOTIFICATIONS_SEEN = 'OVERVIEW_NOTIFICATIONS_SEEN';
